// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBykebVR1opvTgzMX85b9eFYcTr1Zbv-Zs',
    appId: '1:36780693824:web:e3fc2deb9cd5e2577702a5',
    messagingSenderId: '36780693824',
    projectId: 'app-escuela-7c755',
    authDomain: 'app-escuela-7c755.firebaseapp.com',
    storageBucket: 'app-escuela-7c755.firebasestorage.app',
    measurementId: 'G-FW9R39J1WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5mZdVSNrl8gCOn7c4PvdvAFlVbvT37Uc',
    appId: '1:36780693824:android:5b96e6bd1f0451797702a5',
    messagingSenderId: '36780693824',
    projectId: 'app-escuela-7c755',
    storageBucket: 'app-escuela-7c755.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBykebVR1opvTgzMX85b9eFYcTr1Zbv-Zs',
    appId: '1:36780693824:web:fbce37d906244bb97702a5',
    messagingSenderId: '36780693824',
    projectId: 'app-escuela-7c755',
    authDomain: 'app-escuela-7c755.firebaseapp.com',
    storageBucket: 'app-escuela-7c755.firebasestorage.app',
    measurementId: 'G-QC4CQRN0JX',
  );

}